on: [push]
name: Deploiement de l'image Docker sur Azure

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
      
        # ======================= Déploiement sur Azure =======================
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}
              
        #- name: Ckecking des Lint errors avec Hadolint
        #  uses: hadolint/hadolint-action@v3.1.0
        #  with:
        #    dockerfile: Dockerfile
        
        - name: Install Hadolint
          run: sudo apt-get update && sudo apt-get install -y hadolint

        - name: Run Hadolint
          run: hadolint Dockerfile

        - name: Save Hadolint output
          id: hadolint-output
          run: echo "::set-output name=hadolint-output::$(hadolint Dockerfile 2>&1)"

        - name: Use Hadolint output
          run: echo "${{ steps.hadolint-output.outputs.hadolint-output }}"

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
              login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
              docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/20220505:v1
              docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/20220505:v1
        
        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
                resource-group: ${{ secrets.RESOURCE_GROUP }}
                dns-name-label: devops-20220505
                image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20220505:v1
                registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
                registry-username: ${{ secrets.REGISTRY_USERNAME }}
                registry-password: ${{ secrets.REGISTRY_PASSWORD }}
                name: '20220505'
                location: 'france central'
                ports: 8081
                environment-variables: API_KEY=${{ secrets.API_KEY }}
