name: Automatisation du déploiement du container sur DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Scanner du code
      uses: actions/checkout@v3
    - name: Authentification à DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USERNAME_DOCKERHUB }}
        password: ${{ secrets.TOKEN_DOCKERHUB }}
    - name: Ckecking des Lint errors avec Hadolint
    - uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
    - name: Construction du container
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: frimpongefrei/api:2.0.0
