name: Automatisation du déploiement du container sur DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Scanner du code
      uses: actions/checkout@v3
    - name: Authentification à DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.USERNAME_DOCKERHUB }}
        password: ${{ secrets.TOKEN_DOCKERHUB }}
    - name: Ckecking des Lint errors avec Hadolint
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
    - name: Construction du container
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: frimpongefrei/api:2.0.0


# ======================= Déploiement sur Azure =======================
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/20220505:v1
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/20220505:v1

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
            resource-group: ${{ secrets.RESOURCE_GROUP }}
            dns-name-label: devops-20220505
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/20220505:v1
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: 20220505
            location: 'france central'
